version: '3'

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
  db:
    image: mariadb
    volumes:
      - ./sql/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: on-failure
